services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-bookhub
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "TonMotDePasseDocker!"
    volumes:
      - ./init:/init
    command: >
      bash -c "
      /opt/mssql/bin/sqlservr &
      sleep 30 &&
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'TonMotDePasseDocker!' -i /init/init-bookhub.sql -C &&
      wait
      "
